# cattywampus power saving configuration
{
  CPU_DRIVER_OPMODE_ON_AC="guided";
  CPU_DRIVER_OPMODE_ON_BAT="guided";

  CPU_SCALING_GOVERNOR_ON_AC="schedutil";
  CPU_SCALING_GOVERNOR_ON_BAT="schedutil";

  CPU_SCALING_MIN_FREQ_ON_AC=0;
  CPU_SCALING_MAX_FREQ_ON_AC=3500000;
  CPU_SCALING_MIN_FREQ_ON_BAT=0;
  CPU_SCALING_MAX_FREQ_ON_BAT=3500000;

  CPU_ENERGY_PERF_POLICY_ON_AC="balance";
  CPU_ENERGY_PERF_POLICY_ON_BAT="power";
}

